### PR TITLE
Begin to clean up JavaScript

### PR DESCRIPTION
**Pull request by andrewda**
This begins to address some of the concerns listed in #28. These are all formatting changes, nothing technical yet. From my tests everything seems to be working fine, but definitely look over this and test before merging, though, because a large part of it was automated.

When this does get merged, it will be a much more welcoming code base for new contributors.

### CODE REVIEW

**Comment by homakov** [comment]
What about switching to https://standardjs.com ?

**Comment by andrewda** [comment]
@homakov Sure, that sounds good!

**Comment by homakov** [comment]
Thanks, I won't be touching codebase then for a while.

**Comment by andrewda** [comment]
Alright - I'll try to get these done as quickly as possible.

**Comment by andrewda** [comment]
Not at home so haven't tested, but all the StandardJS issues should be fixed in main.js.

**Comment by andrewda** [comment]
Alright @homakov this should be good to go. Any other changes you want made?

**Comment by menzow** [comment]
Awesome job @andrewda. Thanks for implementing one of my suggestions. Btw: You might want to squash your commits before merging. This helps keeping the master branch clean.

`git rebase -i HEAD~13`

**Comment by andrewda** [comment]
Thanks @menzow! Will squash 'em now! 👍

**Comment by andrewda** [comment]
@menzow I squashed them into 4 different commits so it's easier to rollback an individual one if necessary.

**Pull request merged**
